### ISSUE TITLE
OAuth2FlowType.PASSWORD with OAuth2AuthHandler not working

### ISSUE THREAD

**Issue by sashikaxp** [piomin/sample-vertx-microservices#1]
OAuth2FlowType.PASSWORD type does not work with OAuth2AuthHandler in vertx 3.5.0. It requires AUTH_CODE type

**Comment by waytoharish** [comment]
Same issue with me.Getting below error-
SEVERE: OAuth2Auth + Bearer Auth requires OAuth2 AUTH_CODE flow
java.lang.IllegalArgumentException: OAuth2Auth + Bearer Auth requires OAuth2 AUTH_CODE flow
	at io.vertx.ext.web.handler.impl.OAuth2AuthHandlerImpl.verifyProvider(OAuth2AuthHandlerImpl.java:60)
	at io.vertx.ext.web.handler.impl.OAuth2AuthHandlerImpl.<init>(OAuth2AuthHandlerImpl.java:77)
	at io.vertx.ext.web.handler.OAuth2AuthHandler.create(OAuth2AuthHandler.java:42)
	at pl.piomin.services.vertx.account.AccountServer.start(AccountServer.java:56)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:494)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
